name: news_curation_frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev, which is inappropriate for private projects.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.11.0' # Added SDK constraint

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^1.2.1
  intl: ^0.18.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
